import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import { Gabarito } from 'next/font/google'

const gabarito = Gabarito({subsets: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} bg-dark antialiased`}
        suppressHydrationWarning={true}
      >
        <div>
          <NavBar />
        </div>
        {children}
        <div className="h-20">

        </div>
      </body>
    </html>
  );
}
